external config; don't override ucol call..

diff --git a/mkdirinst b/mkdirinst
--- a/mkdirinst
+++ b/mkdirinst
@@ -1,23 +1,26 @@
 #!/bin/sh
 
-# --- BEGIN CONFIG
+conf="/etc/mkdirinst.conf"
 
-# version to be used (current, 14.1, 13.37, etc.)
-version=current
-# architecture : 64, arm or nothing (x86)
-arch=64
-# mirror from which packages should be fetched
-mirror=http://slackware.mirrors.ovh.net/ftp.slackware.com/slackware$arch-$version/
-# installation directory
-root=/mnt/slack64
-# packages template
-template=templates/base
-# timezone
-timezone=Europe/Paris
-# LANG env variable
-lang=en_US.UTF8
+if [ "$1" != "" ]; then
+	conf="$1"
+fi
 
-# --- END CONFIG
+. $conf || exit 1
+
+cat <<EOF
+--- BEGIN CONFIG
+	version=$version
+	arch=$arch
+	mirror=$mirror
+	root=$root
+	template=$template
+	timezone=$timezone
+	lang=$lang
+--- END CONFIG
+EOF
+
+echo 'Continue? (^C to abort)'; read
 
 # temporary directory (mktemp -d?)
 tmp=/tmp/mkdirinst.$$
@@ -70,11 +73,10 @@ grep $root /etc/mtab && \
 	cat $tmp/fstab
 	echo '--- END /etc/fstab'
 
-	echo 'Ok? ^C to abort, file is ' $tmp/fstab
-	read
+	echo 'Ok? ^C to abort, file is ' $tmp/fstab; read
 	# See github.com/heaumer/utils/tree/master/ucol.c
-	which ucol &>/dev/null && (ucol -n 5 $tmp/fstab > $root/etc/fstab)
-	cp $tmp/fstab $root/etc/
+	which ucol &>/dev/null && (ucol -n 5 $tmp/fstab > $root/etc/fstab) || \
+		cp $tmp/fstab $root/etc/
 )
 
 rm -rf $tmp
